### ISSUE TITLE
Add svn status

### ISSUE THREAD

**Issue by mholo65** [cake-contrib/Cake.Svn#2]
Add support for `svn status` command

**Comment by InKahootz** [comment]
I'm actually taking a stab at this one right now. I'll submit a PR soonish (hopefully) and can work on feedback for it. The big question I'm having right now is what result should I return from `SnvSharp.SvnClient.Status`... specifically what from a collection of `SvnStatusEvengArgs` should I convert into `IEnumerable<SvnStatusResult>`.
