### ISSUE TITLE
Update NSubstitue to 3.0.1

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Svn#31]
Update NSubstitue to 3.0.1

**Comment by DanielHutt** [comment]
Looks like you're on this one?

**Comment by pascalberger** [comment]
@DanielHutt Yes there is already an open PR for this: https://github.com/cake-contrib/Cake.Svn/commit/a0c646fbacf8198d24c40a7dff670498200fd3a9

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-contrib/Cake.Svn/pull/32
