### ISSUE TITLE
Add missing mappings for SvnSettings

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.Svn#42]
Prequisites #41 
Add mappings to the following classes
SvnAddSettingsExtensions
SvnDeleteSettingsExtensions
SvnInfoSettingsExtensions
SvnExportSettingsExtensions

Add Tests

**Comment by pascalberger** [comment]
@christianbumann What about SvnExport alias?

**Comment by christianbumann** [comment]
@pascalberger yes we should also extend this alias

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-contrib/Cake.Svn/pull/49
