### ISSUE TITLE
Move SettingsExtensions to correct namespace

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.Svn#43]
Move SvnInfoSettingsExtensions to info namespace
Move SvnExportSettingsExtensions to export namespace

**Comment by dasdachs** [comment]
I just did a pull request. Haven't checked that you assigned it to @x-jokay. Sorry for that.

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-contrib/Cake.Svn/pull/45
