### ISSUE TITLE
GetSvnFileInfo throws an exception when no SvnInfoResult was returned

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.Svn#47]
GetSvnFileInfo should return default SvnInfoSettings when no information about the file was found on Subversion. For this SvnInfoSettings.ThrowOnError has to be set to false and pass as parameter to GetSvnFileInfo.

SvnAliases.Info -> GetSvnFileInfo -> return svnInformation.GetInfo(filePath, settings ?? new SvnInfoSettings()).Single();

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-contrib/Cake.Svn/pull/49
