### ISSUE TITLE
Add svn info

### ISSUE THREAD

**Issue by mholo65** [cake-contrib/Cake.Svn#8]
Add support for returning informationen about repository.

**Comment by pascalberger** [comment]
Can be implemented using [SvnClient.GetInfo](http://docs.sharpsvn.net/current/html/M_SharpSvn_SvnClient_GetInfo.htm)

**Comment by christianbumann** [comment]
@mholo65 it is ok that I implement in a first draft a new class which contains only a few properties which are set on the SvnInfoEventArgs (class from SharpSvn)

**Comment by mholo65** [comment]
@christianbumann, well `svn info` only checks local copy, so a `DirectoryPath` or `FilePath` should be sufficient as arg. Regarding return type, let’s try to hide `SharpSvn` from the API by creating an abstraction around it, less surprises for `Cake.Svn` users when `SharpSvn` is updated.

**Comment by mholo65** [comment]
Sounds good to me!

**Comment by mholo65** [comment]
Sorry, my bad. Remote info should also be supported. So a `Url` overload which also takes `SvnInfoSettings` (which inherits from `SvnRemoteSettings`) could also he added. See SvnExport implementation for an example.
